#include "K2Node_QueueControlFlowRepeat.h"

#include "ControlFlowBP.h"

#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "KismetCompiler.h"
#include "Styling/AppStyle.h"

#define LOCTEXT_NAMESPACE "K2Node_QueueControlFlowRepeat"

const FName UK2Node_QueueControlFlowRepeat::PN_Count(TEXT("Count"));
const FName UK2Node_QueueControlFlowRepeat::PN_IterationFunction(TEXT("IterationFunction"));

void UK2Node_QueueControlFlowRepeat::CreateStepPins()
{
	UEdGraphPin* CountPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, PN_Count);
	CountPin->PinToolTip = LOCTEXT("CountTooltip", "How many iterations to run. 0 or less runs none.").ToString();
	CountPin->DefaultValue = CountPin->AutogeneratedDefaultValue = TEXT("1");

	CreatePickPin(LOCTEXT("IterationPin", "Iteration"),
		LOCTEXT("IterationTooltip", "The function or custom event on this Blueprint that builds each iteration: it takes a Control Flow Loop and queues the iteration's steps onto its Get Body."));
}

FText UK2Node_QueueControlFlowRepeat::GetBaseTitle() const
{
	return LOCTEXT("Title", "Queue Repeat");
}

FText UK2Node_QueueControlFlowRepeat::GetPickLabel() const
{
	return LOCTEXT("PickLabel", "Iteration");
}

void UK2Node_QueueControlFlowRepeat::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	FName ResolvedName;
	const UFunction* Iteration = ResolvePickedFunction(&ResolvedName);
	if (!CheckTargetConnected(CompilerContext) || !Iteration || !Fits(Iteration, nullptr))
	{
		BreakAllNodeLinks();
		return;
	}

	static const FName TaskNameParam(TEXT("TaskName"));
	static const FName BuildIterationParam(TEXT("BuildIteration"));

	bool bSucceeded = true;
	UK2Node_CallFunction* CallNode = SpawnQueueCall(CompilerContext, SourceGraph,
		GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueRepeat), TaskNameParam, bSucceeded);

	if (CallNode)
	{
		MoveToCall(CompilerContext, CallNode, PN_Count, PN_Count, bSucceeded);
		bSucceeded &= ConnectEvent(CompilerContext, SourceGraph, CallNode->FindPin(BuildIterationParam, EGPD_Input), ResolvedName);

		if (!bSucceeded)
		{
			ReportExpansionFailed(CompilerContext);
		}
	}

	BreakAllNodeLinks();
}

FText UK2Node_QueueControlFlowRepeat::GetTooltipText() const
{
	return LOCTEXT("Tooltip",
		"Queues a loop that runs Iteration's steps Count times.\n\n"
		"Iteration is picked from this Blueprint's own functions and custom events. It takes a Control Flow Loop and runs once per iteration: "
		"queue that iteration's steps onto the loop's Get Body. Get Iteration Index counts from 0.");
}

FText UK2Node_QueueControlFlowRepeat::GetKeywords() const
{
	return LOCTEXT("Keywords", "control flow queue repeat loop times count for");
}

FSlateIcon UK2Node_QueueControlFlowRepeat::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = GetNodeTitleColor();
	static const FSlateIcon Icon(FAppStyle::GetAppStyleSetName(), TEXT("GraphEditor.Macro.Loop_16x"));
	return Icon;
}

FText UK2Node_QueueControlFlowRepeat::GetNoFunctionsLabel(const UEdGraphPin&) const
{
	return LOCTEXT("NoFunctions", "(no functions or events on this Blueprint take a Control Flow Loop yet)");
}

FText UK2Node_QueueControlFlowRepeat::GetFunctionPinHint(const UEdGraphPin&) const
{
	return LOCTEXT("PickHint",
		"Functions and custom events on this Blueprint that take a Control Flow Loop.\n"
		"Runs once per iteration: queue that iteration's steps onto the loop's Get Body.");
}

#undef LOCTEXT_NAMESPACE
