#include "K2Node_QueueControlFlowWaitUntil.h"

#include "ControlFlowBP.h"

#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "KismetCompiler.h"
#include "UObject/UnrealType.h"

#define LOCTEXT_NAMESPACE "K2Node_QueueControlFlowWaitUntil"

const FName UK2Node_QueueControlFlowWaitUntil::PN_ConditionFunction(TEXT("ConditionFunction"));
const FName UK2Node_QueueControlFlowWaitUntil::PN_CheckInterval(TEXT("CheckInterval"));
const FName UK2Node_QueueControlFlowWaitUntil::PN_TimeoutSeconds(TEXT("TimeoutSeconds"));

void UK2Node_QueueControlFlowWaitUntil::CreateStepPins()
{
	CreatePickPin(LOCTEXT("ConditionPin", "Condition"),
		LOCTEXT("ConditionTooltip", "The function on this Blueprint that says when to stop waiting: it takes nothing and returns a bool."));

	UEdGraphPin* IntervalPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, PN_CheckInterval);
	IntervalPin->PinFriendlyName = LOCTEXT("CheckIntervalPin", "Check Interval");
	IntervalPin->PinToolTip = LOCTEXT("CheckIntervalTooltip", "Seconds of game time between checks of Condition. 0 checks every frame.").ToString();
	IntervalPin->DefaultValue = IntervalPin->AutogeneratedDefaultValue = TEXT("0.0");
	IntervalPin->bAdvancedView = true;

	UEdGraphPin* TimeoutPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, PN_TimeoutSeconds);
	TimeoutPin->PinFriendlyName = LOCTEXT("TimeoutPin", "Timeout Seconds");
	TimeoutPin->PinToolTip = LOCTEXT("TimeoutTooltip",
		"Fail the step if Condition is still false after this many seconds of game time - time spent paused does not count. "
		"-1 uses the flow's Default Step Timeout (set on Create Control Flow), 0 waits forever.").ToString();
	TimeoutPin->DefaultValue = TimeoutPin->AutogeneratedDefaultValue = TEXT("-1.0");
}

FText UK2Node_QueueControlFlowWaitUntil::GetBaseTitle() const
{
	return LOCTEXT("Title", "Queue Wait Until");
}

FText UK2Node_QueueControlFlowWaitUntil::GetPickLabel() const
{
	return LOCTEXT("PickLabel", "Condition");
}

bool UK2Node_QueueControlFlowWaitUntil::Fits(const UFunction* Function, FString* OutWhyNot) const
{
	FString Why;
	const bool bFits = UControlFlowBP::IsConditionFunction(Function, Why);

	if (OutWhyNot)
	{
		*OutWhyNot = MoveTemp(Why);
	}

	return bFits;
}

UFunction* UK2Node_QueueControlFlowWaitUntil::GetPickSignature() const
{
	static const FName ConditionParam(TEXT("Condition"));

	const UFunction* WaitUntil = UControlFlowBP::StaticClass()->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueWaitUntil));
	const FDelegateProperty* Param = WaitUntil ? CastField<FDelegateProperty>(WaitUntil->FindPropertyByName(ConditionParam)) : nullptr;
	return Param ? Param->SignatureFunction.Get() : nullptr;
}

void UK2Node_QueueControlFlowWaitUntil::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	FName ResolvedName;
	const UFunction* Condition = ResolvePickedFunction(&ResolvedName);
	if (!CheckTargetConnected(CompilerContext) || !Condition || !Fits(Condition, nullptr))
	{
		BreakAllNodeLinks();
		return;
	}

	static const FName OwnerParam(TEXT("Owner"));
	static const FName StepNameParam(TEXT("StepName"));

	bool bSucceeded = true;
	UK2Node_CallFunction* CallNode = SpawnQueueCall(CompilerContext, SourceGraph,
		GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueWaitUntilByName), StepNameParam, bSucceeded);

	if (CallNode)
	{
		MoveToCall(CompilerContext, CallNode, PN_CheckInterval, PN_CheckInterval, bSucceeded);
		MoveToCall(CompilerContext, CallNode, PN_TimeoutSeconds, PN_TimeoutSeconds, bSucceeded);

		if (UEdGraphPin* ConditionPin = CallNode->FindPin(PN_ConditionFunction, EGPD_Input))
		{
			ConditionPin->DefaultValue = ResolvedName.ToString();
		}
		else
		{
			bSucceeded = false;
		}

		bSucceeded &= ConnectSelf(CompilerContext, SourceGraph, CallNode->FindPin(OwnerParam, EGPD_Input));

		if (!bSucceeded)
		{
			ReportExpansionFailed(CompilerContext);
		}
	}

	BreakAllNodeLinks();
}

FText UK2Node_QueueControlFlowWaitUntil::GetTooltipText() const
{
	return LOCTEXT("Tooltip",
		"Queues a Wait step that finishes once Condition returns true. Condition is asked when the step is reached, then every Check Interval "
		"seconds (0: every frame) - but not while the game is paused.\n\n"
		"Condition is picked from this Blueprint's own functions: it takes nothing and returns a bool - a pure function will do, and its output "
		"may have any name.\n\n"
		"If Condition is still false after Timeout Seconds, the step fails.");
}

FText UK2Node_QueueControlFlowWaitUntil::GetKeywords() const
{
	return LOCTEXT("Keywords", "control flow queue wait until condition poll bool true");
}

FText UK2Node_QueueControlFlowWaitUntil::GetNoFunctionsLabel(const UEdGraphPin&) const
{
	return LOCTEXT("NoFunctions", "(no functions on this Blueprint return just a bool yet)");
}

FText UK2Node_QueueControlFlowWaitUntil::GetFunctionPinHint(const UEdGraphPin&) const
{
	return LOCTEXT("PickHint",
		"Functions on this Blueprint that take nothing and return a bool - pure or not, whatever the output is called.\n"
		"Asked when the step is reached, then every Check Interval seconds until it returns true.");
}

#undef LOCTEXT_NAMESPACE
