#include "K2Node_QueueControlFlowWaitForDispatcher.h"

#include "ControlFlowBP.h"
#include "ControlFlowBPNodeUtils.h"

#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "KismetCompiler.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "ScopedTransaction.h"
#include "Styling/AppStyle.h"

#define LOCTEXT_NAMESPACE "K2Node_QueueControlFlowWaitForDispatcher"

const FName UK2Node_QueueControlFlowWaitForDispatcher::PN_DispatcherName(TEXT("DispatcherName"));
const FName UK2Node_QueueControlFlowWaitForDispatcher::PN_TimeoutSeconds(TEXT("TimeoutSeconds"));

void UK2Node_QueueControlFlowWaitForDispatcher::CreateStepPins()
{
	UEdGraphPin* ObjectPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), UEdGraphSchema_K2::PN_Self);
	ObjectPin->PinFriendlyName = LOCTEXT("ObjectPin", "Object");
	ObjectPin->PinToolTip = LOCTEXT("ObjectTooltip", "The object whose event dispatcher to wait for. Unconnected, this Blueprint itself.").ToString();

	CreatePickPin(LOCTEXT("DispatcherPin", "Event Dispatcher"),
		LOCTEXT("DispatcherTooltip", "One of Object's event dispatchers, Blueprint or C++. The step finishes the next time it is called."));

	UEdGraphPin* TimeoutPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, PN_TimeoutSeconds);
	TimeoutPin->PinFriendlyName = LOCTEXT("TimeoutPin", "Timeout Seconds");
	TimeoutPin->PinToolTip = LOCTEXT("TimeoutTooltip",
		"Fail the step if the dispatcher has not been called after this many seconds of game time - time spent paused does not count. "
		"-1 uses the flow's Default Step Timeout (set on Create Control Flow), 0 waits forever.").ToString();
	TimeoutPin->DefaultValue = TimeoutPin->AutogeneratedDefaultValue = TEXT("-1.0");
}

FText UK2Node_QueueControlFlowWaitForDispatcher::GetBaseTitle() const
{
	return LOCTEXT("Title", "Queue Wait For Event Dispatcher");
}

FText UK2Node_QueueControlFlowWaitForDispatcher::GetPickLabel() const
{
	return LOCTEXT("PickLabel", "Event Dispatcher");
}

bool UK2Node_QueueControlFlowWaitForDispatcher::IsObjectSelf() const
{
	const UEdGraphPin* ObjectPin = FindPin(UEdGraphSchema_K2::PN_Self, EGPD_Input);
	return !ObjectPin || ObjectPin->LinkedTo.Num() == 0 || ObjectPin->LinkedTo[0]->PinType.PinSubCategory == UEdGraphSchema_K2::PSC_Self;
}

const UClass* UK2Node_QueueControlFlowWaitForDispatcher::GetObjectClass() const
{
	using namespace UE::ControlFlowBP;

	if (IsObjectSelf())
	{
		return NodeUtils::GetSearchClass(FBlueprintEditorUtils::FindBlueprintForNode(this));
	}

	const UEdGraphPin* ObjectPin = FindPin(UEdGraphSchema_K2::PN_Self, EGPD_Input);
	const UClass* Class = Cast<UClass>(ObjectPin->LinkedTo[0]->PinType.PinSubCategoryObject.Get());

	const UBlueprint* ClassBlueprint = UBlueprint::GetBlueprintFromClass(Class);
	return ClassBlueprint ? NodeUtils::GetSearchClass(ClassBlueprint) : Class;
}

FName UK2Node_QueueControlFlowWaitForDispatcher::ResolvePickedName() const
{
	using namespace UE::ControlFlowBP;

	const UClass* Class = GetObjectClass();
	if (!Class || Picked.Name.IsNone() || NodeUtils::GetEventDispatchers(Class).Contains(Picked.Name))
	{
		return Picked.Name;
	}

	const FName Renamed = NodeUtils::FindDispatcherNameByGuid(Class, Picked.Guid);
	return Renamed.IsNone() ? Picked.Name : Renamed;
}

FGuid UK2Node_QueueControlFlowWaitForDispatcher::FindPickGuid(FName Name) const
{
	return UE::ControlFlowBP::NodeUtils::FindDispatcherGuid(GetObjectClass(), Name);
}

void UK2Node_QueueControlFlowWaitForDispatcher::HandleVariableRenamed(UBlueprint* InBlueprint, UClass* InVariableClass, UEdGraph* InGraph, const FName& InOldVarName, const FName& InNewVarName)
{
	Super::HandleVariableRenamed(InBlueprint, InVariableClass, InGraph, InOldVarName, InNewVarName);

	if (ReferencesVariable(InOldVarName, InVariableClass))
	{
		Modify();
		Picked.Name = InNewVarName;
		MirrorPropertiesToPins();
	}
}

bool UK2Node_QueueControlFlowWaitForDispatcher::ReferencesVariable(const FName& InVarName, const UStruct* InScope) const
{
	return !Picked.Name.IsNone() && Picked.Name == InVarName && UE::ControlFlowBP::NodeUtils::IsClassOrChildOf(GetObjectClass(), InScope);
}

void UK2Node_QueueControlFlowWaitForDispatcher::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	using namespace UE::ControlFlowBP;

	Super::ExpandNode(CompilerContext, SourceGraph);

	if (!CheckTargetConnected(CompilerContext) || Picked.Name.IsNone())
	{
		BreakAllNodeLinks();
		return;
	}

	const UClass* ObjectClass = GetObjectClass();
	const FName DispatcherName = ResolvePickedName();
	if (ObjectClass && !NodeUtils::GetEventDispatchers(ObjectClass).Contains(DispatcherName))
	{
		CompilerContext.MessageLog.Error(*FText::Format(
			LOCTEXT("NoSuchDispatcher", "@@: {0} has no event dispatcher named '{1}'. Pick one of its own, or cast Object to the type that has it."),
			FBlueprintEditorUtils::GetFriendlyClassDisplayName(ObjectClass), FText::FromName(DispatcherName)).ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	static const FName ObjectParam(TEXT("Target"));
	static const FName StepNameParam(TEXT("StepName"));

	bool bSucceeded = true;
	UK2Node_CallFunction* CallNode = SpawnQueueCall(CompilerContext, SourceGraph,
		GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueWaitForEventDispatcher), StepNameParam, bSucceeded);

	if (CallNode)
	{
		MoveToCall(CompilerContext, CallNode, PN_TimeoutSeconds, PN_TimeoutSeconds, bSucceeded);

		if (UEdGraphPin* NamePin = CallNode->FindPin(PN_DispatcherName, EGPD_Input))
		{
			NamePin->DefaultValue = DispatcherName.ToString();
		}
		else
		{
			bSucceeded = false;
		}

		const UEdGraphPin* ObjectPin = FindPin(UEdGraphSchema_K2::PN_Self, EGPD_Input);
		if (ObjectPin && ObjectPin->LinkedTo.Num() > 0)
		{
			MoveToCall(CompilerContext, CallNode, UEdGraphSchema_K2::PN_Self, ObjectParam, bSucceeded);
		}
		else
		{
			bSucceeded &= ConnectSelf(CompilerContext, SourceGraph, CallNode->FindPin(ObjectParam, EGPD_Input));
		}

		if (!bSucceeded)
		{
			ReportExpansionFailed(CompilerContext);
		}
	}

	BreakAllNodeLinks();
}

FText UK2Node_QueueControlFlowWaitForDispatcher::GetTooltipText() const
{
	return LOCTEXT("Tooltip",
		"Queues a Wait step that finishes the next time one of Object's event dispatchers is called - a Blueprint event dispatcher, or a C++ "
		"one such as On Destroyed. The dispatcher's parameters are not read.\n\n"
		"The dropdown lists the dispatchers of the type Object is connected to; unconnected, this Blueprint's own.\n\n"
		"If the dispatcher is not called within Timeout Seconds, the step fails.");
}

FText UK2Node_QueueControlFlowWaitForDispatcher::GetKeywords() const
{
	return LOCTEXT("Keywords", "control flow queue wait event dispatcher delegate signal broadcast");
}

FSlateIcon UK2Node_QueueControlFlowWaitForDispatcher::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = GetNodeTitleColor();
	static const FSlateIcon Icon(FAppStyle::GetAppStyleSetName(), TEXT("GraphEditor.Delegate_16x"));
	return Icon;
}

TArray<FName> UK2Node_QueueControlFlowWaitForDispatcher::GetPickableFunctions(const UEdGraphPin& Pin) const
{
	return IsFunctionPin(Pin) ? UE::ControlFlowBP::NodeUtils::GetEventDispatchers(GetObjectClass()) : TArray<FName>();
}

FText UK2Node_QueueControlFlowWaitForDispatcher::GetCreateFunctionLabel(const UEdGraphPin& Pin) const
{
	if (!IsFunctionPin(Pin) || !IsObjectSelf() || !FBlueprintEditorUtils::FindBlueprintForNode(this))
	{
		return FText::GetEmpty();
	}

	return LOCTEXT("CreateDispatcher", "[Create a new event dispatcher]");
}

UObject* UK2Node_QueueControlFlowWaitForDispatcher::CreateFunctionFor(const UEdGraphPin& Pin)
{
	using namespace UE::ControlFlowBP;

	UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this);
	if (!Blueprint || GetCreateFunctionLabel(Pin).IsEmpty())
	{
		return nullptr;
	}

	const FScopedTransaction Transaction(LOCTEXT("CreateDispatcherTransaction", "Create Event Dispatcher"));
	Modify();

	const FName Name = NodeUtils::AddEventDispatcher(Blueprint, TEXT("NewEventDispatcher"));
	if (Name.IsNone())
	{
		return nullptr;
	}

	SetPick(Name);

	return NodeUtils::FindDispatcherGraph(GetObjectClass(), Name);
}

FText UK2Node_QueueControlFlowWaitForDispatcher::GetNoFunctionsLabel(const UEdGraphPin&) const
{
	const UClass* Class = GetObjectClass();
	return Class
		? FText::Format(LOCTEXT("NoDispatchers", "({0} has no event dispatchers)"), FBlueprintEditorUtils::GetFriendlyClassDisplayName(Class))
		: LOCTEXT("NoDispatchersUnknownType", "(no event dispatchers)");
}

FText UK2Node_QueueControlFlowWaitForDispatcher::GetFunctionPinHint(const UEdGraphPin&) const
{
	return LOCTEXT("PickHint",
		"The event dispatchers of the type Object is connected to - its own and inherited, Blueprint and C++ such as On Destroyed.\n"
		"The step finishes the next time the one picked is called.");
}

UObject* UK2Node_QueueControlFlowWaitForDispatcher::GetFunctionDefinition(const UEdGraphPin& Pin) const
{
	return IsFunctionPin(Pin) ? UE::ControlFlowBP::NodeUtils::FindDispatcherGraph(GetObjectClass(), ResolvePickedName()) : nullptr;
}

FText UK2Node_QueueControlFlowWaitForDispatcher::GetPickPrompt(const UEdGraphPin&) const
{
	return LOCTEXT("PickPrompt", "Select Event Dispatcher...");
}

#undef LOCTEXT_NAMESPACE
