#include "K2Node_QueueControlFlowStep.h"

#include "ControlFlowBP.h"
#include "ControlFlowBPNodeUtils.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "K2Node_CreateDelegate.h"
#include "K2Node_CustomEvent.h"
#include "K2Node_Self.h"
#include "KismetCompiler.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/CompilerResultsLog.h"
#include "ScopedTransaction.h"
#include "StructUtils/InstancedStruct.h"
#include "Styling/AppStyle.h"
#include "UObject/UnrealType.h"

#define LOCTEXT_NAMESPACE "K2Node_QueueControlFlowStep"

const FName UK2Node_QueueControlFlowStep::PN_Target(TEXT("Target"));
const FName UK2Node_QueueControlFlowStep::PN_StepKind(TEXT("StepKind"));
const FName UK2Node_QueueControlFlowStep::PN_Function(TEXT("Function"));
const FName UK2Node_QueueControlFlowStep::PN_StepName(TEXT("StepName"));
const FName UK2Node_QueueControlFlowStep::PN_Payload(TEXT("Payload"));
const FName UK2Node_QueueControlFlowStep::PN_Flow(TEXT("Flow"));
const FName UK2Node_QueueControlFlowStep::PN_TimeoutSeconds(TEXT("TimeoutSeconds"));
const FName UK2Node_QueueControlFlowStep::PN_ForkMode(TEXT("ForkMode"));
const FName UK2Node_QueueControlFlowStep::PN_LoopMode(TEXT("LoopMode"));
const FName UK2Node_QueueControlFlowStep::PN_MaxIterations(TEXT("MaxIterations"));
const FName UK2Node_QueueControlFlowStep::PN_Seconds(TEXT("Seconds"));

namespace UE::ControlFlowBP::QueueStepNode
{
	static bool IsStepCandidate(const UFunction* Function, const UClass* SelfClass)
	{
		return NodeUtils::IsPickableFunction(Function, SelfClass) && UEdGraphSchema_K2::FunctionCanBeUsedInDelegate(Function);
	}
}

void UK2Node_QueueControlFlowStep::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* TargetPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UControlFlowBP::StaticClass(), PN_Target);
	TargetPin->PinToolTip = LOCTEXT("TargetTooltip", "The flow to queue this step onto.").ToString();

	UEdGraphPin* KindPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, StaticEnum<EControlFlowStepKind>(), PN_StepKind);
	KindPin->PinFriendlyName = LOCTEXT("StepKindPin", "Step Kind");
	KindPin->PinToolTip = LOCTEXT("StepKindTooltip", "What kind of step this is. Filters the Function dropdown to the functions whose signature fits. Delay runs no function: it waits Seconds instead.").ToString();
	KindPin->AutogeneratedDefaultValue = KindToString(EControlFlowStepKind::Function);
	KindPin->bNotConnectable = true;

	UEdGraphPin* FunctionPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, PN_Function);
	FunctionPin->PinToolTip = LOCTEXT("FunctionTooltip", "The function or custom event on this Blueprint that runs the step.").ToString();
	FunctionPin->bNotConnectable = true;

	UEdGraphPin* NamePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_String, PN_StepName);
	NamePin->PinFriendlyName = LOCTEXT("StepNamePin", "Step Name");
	NamePin->PinToolTip = LOCTEXT("StepNameTooltip", "Shown in logs and Get Current Step Path. Defaults to the function's name.").ToString();
	NamePin->bAdvancedView = true;

	UEdGraphPin* PayloadPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FInstancedStruct::StaticStruct(), PN_Payload);
	PayloadPin->PinToolTip = LOCTEXT("PayloadTooltip", "Data handed back to the step: Get Payload on its handle or scope, or as the event's only parameter for a Function step.").ToString();
	PayloadPin->bAdvancedView = true;

	UEdGraphPin* FlowPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Object, UControlFlowBP::StaticClass(), PN_Flow);
	FlowPin->PinToolTip = LOCTEXT("FlowTooltip", "The same flow, so steps chain.").ToString();

	CreateKindSpecificPins(StepKind);
	MirrorPropertiesToPins();
	UpdateFunctionPinsVisibility();

	if (AdvancedPinDisplay == ENodeAdvancedPins::NoPins)
	{
		AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
	}

	Super::AllocateDefaultPins();
}

void UK2Node_QueueControlFlowStep::CreateKindSpecificPins(EControlFlowStepKind Kind)
{
	switch (Kind)
	{
	case EControlFlowStepKind::Wait:
		{
			UEdGraphPin* Pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, PN_TimeoutSeconds);
			Pin->PinFriendlyName = LOCTEXT("TimeoutPin", "Timeout Seconds");
			Pin->PinToolTip = LOCTEXT("TimeoutTooltip", "Fail the step if its handle is not resolved within this many seconds of game time - time spent paused does not count. -1 uses the flow's Default Step Timeout (set on Create Control Flow), 0 waits forever.").ToString();
			Pin->DefaultValue = Pin->AutogeneratedDefaultValue = TEXT("-1.0");
			break;
		}

	case EControlFlowStepKind::Fork:
		{
			UEdGraphPin* Pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, StaticEnum<EControlFlowConcurrency>(), PN_ForkMode);
			Pin->PinFriendlyName = LOCTEXT("ForkModePin", "Mode");
			Pin->DefaultValue = Pin->AutogeneratedDefaultValue =
				StaticEnum<EControlFlowConcurrency>()->GetNameStringByValue(static_cast<int64>(EControlFlowConcurrency::Ordered));
			break;
		}

	case EControlFlowStepKind::Loop:
		{
			UEdGraphPin* ModePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, StaticEnum<EControlFlowLoopMode>(), PN_LoopMode);
			ModePin->PinFriendlyName = LOCTEXT("LoopModePin", "Mode");
			ModePin->DefaultValue = ModePin->AutogeneratedDefaultValue =
				StaticEnum<EControlFlowLoopMode>()->GetNameStringByValue(static_cast<int64>(EControlFlowLoopMode::DoWhile));

			UEdGraphPin* MaxPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, PN_MaxIterations);
			MaxPin->PinFriendlyName = LOCTEXT("MaxIterationsPin", "Max Iterations");
			MaxPin->PinToolTip = LOCTEXT("MaxIterationsTooltip", "0, the default, lets the loop run until its function answers Continue Looping false or the flow is cancelled. Above 0, a loop that asks for more iterations than that is stopped with an error - a backstop for a loop that is meant to end.").ToString();
			MaxPin->DefaultValue = MaxPin->AutogeneratedDefaultValue = TEXT("0");
			MaxPin->bAdvancedView = true;
			break;
		}

	case EControlFlowStepKind::Delay:
		{
			UEdGraphPin* Pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, PN_Seconds);
			Pin->PinToolTip = LOCTEXT("SecondsTooltip", "How long the flow waits, in seconds of game time - like a Delay node, it stands still while the game is paused. 0 waits for the next frame.").ToString();
			Pin->DefaultValue = Pin->AutogeneratedDefaultValue = TEXT("1.0");
			break;
		}

	default:
		break;
	}
}

bool UK2Node_QueueControlFlowStep::IsKindSpecificPin(const UEdGraphPin* Pin)
{
	return Pin
		&& (Pin->PinName == PN_TimeoutSeconds
			|| Pin->PinName == PN_ForkMode
			|| Pin->PinName == PN_LoopMode
			|| Pin->PinName == PN_MaxIterations
			|| Pin->PinName == PN_Seconds);
}

void UK2Node_QueueControlFlowStep::SyncKindSpecificPins()
{
	TArray<UEdGraphPin*> OldPins;
	for (UEdGraphPin* Pin : Pins)
	{
		if (IsKindSpecificPin(Pin))
		{
			OldPins.Add(Pin);
		}
	}

	for (UEdGraphPin* Pin : OldPins)
	{
		Pins.Remove(Pin);
	}

	CreateKindSpecificPins(StepKind);

	RewireOldPinsToNewPins(OldPins, Pins, nullptr);

	UpdateFunctionPinsVisibility();

	if (UEdGraph* Graph = GetGraph())
	{
		Graph->NotifyGraphChanged();
	}

	if (UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this))
	{
		FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
	}
}

void UK2Node_QueueControlFlowStep::UpdateFunctionPinsVisibility()
{
	const bool bHidden = StepKind == EControlFlowStepKind::Delay;

	for (const FName PinName : { PN_Function, PN_Payload })
	{
		if (UEdGraphPin* Pin = FindPin(PinName, EGPD_Input))
		{
			if (bHidden)
			{
				Pin->BreakAllPinLinks(true);
			}

			Pin->bHidden = bHidden;
		}
	}
}

void UK2Node_QueueControlFlowStep::MirrorPropertiesToPins()
{
	if (UEdGraphPin* KindPin = FindPin(PN_StepKind))
	{
		KindPin->DefaultValue = KindToString(StepKind);
	}

	if (UEdGraphPin* FunctionPin = FindPin(PN_Function))
	{
		FunctionPin->DefaultValue = FunctionName.IsNone() ? FString() : FunctionName.ToString();
	}
}

void UK2Node_QueueControlFlowStep::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (!Pin)
	{
		return;
	}

	if (Pin->PinName == PN_StepKind)
	{
		const EControlFlowStepKind NewKind = KindFromString(Pin->DefaultValue);
		if (NewKind == StepKind)
		{
			return;
		}

		Modify();
		StepKind = NewKind;

		const UFunction* Current = ResolveStepFunction();
		FString Unused;
		if (StepKind == EControlFlowStepKind::Delay
			|| (Current && ResolveKind(UControlFlowBP::DeduceStepKind(Current, Unused), StepKind) != StepKind))
		{
			SetFunctionInternal(NAME_None);
		}

		SyncKindSpecificPins();
	}
	else if (Pin->PinName == PN_Function)
	{
		const FName NewName(*Pin->DefaultValue);
		if (NewName == FunctionName)
		{
			return;
		}

		Modify();
		SetFunctionInternal(NewName);

		FollowFunctionKind();
		SyncKindSpecificPins();
	}
}

FString UK2Node_QueueControlFlowStep::KindToString(EControlFlowStepKind Kind)
{
	return StaticEnum<EControlFlowStepKind>()->GetNameStringByValue(static_cast<int64>(Kind));
}

EControlFlowStepKind UK2Node_QueueControlFlowStep::KindFromString(const FString& Value)
{
	const int64 Parsed = StaticEnum<EControlFlowStepKind>()->GetValueByNameString(Value);
	if (Parsed == INDEX_NONE || Parsed == static_cast<int64>(EControlFlowStepKind::Invalid))
	{
		return EControlFlowStepKind::Function;
	}

	return static_cast<EControlFlowStepKind>(Parsed);
}

UFunction* UK2Node_QueueControlFlowStep::ResolveStepFunction(FName* OutResolvedName) const
{
	return UE::ControlFlowBP::NodeUtils::ResolveFunction(FBlueprintEditorUtils::FindBlueprintForNode(this), FunctionName, FunctionGuid, OutResolvedName);
}

void UK2Node_QueueControlFlowStep::SetFunctionInternal(FName NewFunctionName)
{
	FunctionName = NewFunctionName;

	const UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this);
	FunctionGuid = UE::ControlFlowBP::NodeUtils::FindFunctionGuid(Blueprint, NewFunctionName);

	if (UEdGraphPin* FunctionPin = FindPin(PN_Function))
	{
		FunctionPin->DefaultValue = NewFunctionName.IsNone() ? FString() : NewFunctionName.ToString();
	}
}

void UK2Node_QueueControlFlowStep::FollowFunctionKind()
{
	const UFunction* Function = ResolveStepFunction();
	if (!Function)
	{
		return;
	}

	FString Unused;
	const EControlFlowStepKind Actual = ResolveKind(UControlFlowBP::DeduceStepKind(Function, Unused), StepKind);
	if (Actual == EControlFlowStepKind::Invalid || Actual == StepKind)
	{
		return;
	}

	StepKind = Actual;

	if (UEdGraphPin* KindPin = FindPin(PN_StepKind))
	{
		KindPin->DefaultValue = KindToString(StepKind);
	}
}

TArray<FName> UK2Node_QueueControlFlowStep::GetCandidateFunctions() const
{
	using namespace UE::ControlFlowBP::QueueStepNode;

	TArray<FName> Names;

	const UClass* Class = UE::ControlFlowBP::NodeUtils::GetSearchClass(FBlueprintEditorUtils::FindBlueprintForNode(this));
	if (!Class)
	{
		return Names;
	}

	for (TFieldIterator<UFunction> It(Class, EFieldIteratorFlags::IncludeSuper); It; ++It)
	{
		const UFunction* Function = *It;
		if (!IsStepCandidate(Function, Class))
		{
			continue;
		}

		FString Unused;
		if (ResolveKind(UControlFlowBP::DeduceStepKind(Function, Unused), StepKind) == StepKind && IsBindable(Function, StepKind))
		{
			Names.AddUnique(Function->GetFName());
		}
	}

	Names.Sort(FNameLexicalLess());
	return Names;
}

UK2Node_QueueControlFlowStep::FQueueCall UK2Node_QueueControlFlowStep::GetQueueCall(EControlFlowStepKind Kind, bool bFunctionTakesPayload)
{
	static const FName Step(TEXT("Step"));
	static const FName Populate(TEXT("Populate"));
	static const FName Define(TEXT("Define"));
	static const FName BuildIteration(TEXT("BuildIteration"));
	static const FName StepName(TEXT("StepName"));
	static const FName TaskName(TEXT("TaskName"));

	switch (Kind)
	{
	case EControlFlowStepKind::Function:
		return bFunctionTakesPayload
			? FQueueCall{ GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueFunction), Step, StepName, true }
			: FQueueCall{ GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueSimpleFunction), Step, StepName, false };

	case EControlFlowStepKind::Wait:
		return FQueueCall{ GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueWait), Step, StepName, true };

	case EControlFlowStepKind::SubFlow:
		return FQueueCall{ GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueSubFlow), Populate, TaskName, true };

	case EControlFlowStepKind::Branch:
		return FQueueCall{ GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueBranch), Define, TaskName, true };

	case EControlFlowStepKind::Fork:
		return FQueueCall{ GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueFork), Define, TaskName, true };

	case EControlFlowStepKind::Race:
		return FQueueCall{ GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueRace), Define, TaskName, true };

	case EControlFlowStepKind::Loop:
		return FQueueCall{ GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueCombinedLoop), BuildIteration, TaskName, true };

	case EControlFlowStepKind::Delay:
		return FQueueCall{ GET_FUNCTION_NAME_CHECKED(UControlFlowBP, QueueDelay), NAME_None, StepName, false };

	default:
		return FQueueCall();
	}
}

EControlFlowStepKind UK2Node_QueueControlFlowStep::ResolveKind(EControlFlowStepKind Deduced, EControlFlowStepKind Chosen)
{
	return (Deduced == EControlFlowStepKind::Fork && Chosen == EControlFlowStepKind::Race) ? EControlFlowStepKind::Race : Deduced;
}

const UFunction* UK2Node_QueueControlFlowStep::GetDelegateSignature(EControlFlowStepKind Kind, bool bFunctionTakesPayload)
{
	const FQueueCall Call = GetQueueCall(Kind, bFunctionTakesPayload);
	if (Call.Function.IsNone() || Call.DelegateParam.IsNone())
	{
		return nullptr;
	}

	const UFunction* Queue = UControlFlowBP::StaticClass()->FindFunctionByName(Call.Function);
	const FDelegateProperty* DelegateParam = Queue ? CastField<FDelegateProperty>(Queue->FindPropertyByName(Call.DelegateParam)) : nullptr;
	return DelegateParam ? DelegateParam->SignatureFunction.Get() : nullptr;
}

bool UK2Node_QueueControlFlowStep::IsBindable(const UFunction* Function, EControlFlowStepKind Kind)
{
	if (!Function)
	{
		return false;
	}

	const UFunction* Signature = GetDelegateSignature(Kind, Function->NumParms > 0);
	return Signature && Signature->IsSignatureCompatibleWith(Function);
}

FText UK2Node_QueueControlFlowStep::GetSignatureHint(EControlFlowStepKind Kind)
{
	switch (Kind)
	{
	case EControlFlowStepKind::Function:
		return LOCTEXT("HintFunction", "A Function step takes nothing, or a single Instanced Struct payload.");
	case EControlFlowStepKind::Wait:
		return LOCTEXT("HintWait", "A Wait step takes a Control Flow Step Handle - resolve it exactly once.");
	case EControlFlowStepKind::SubFlow:
		return LOCTEXT("HintSubFlow", "A Sub Flow step takes a Control Flow to queue the group's steps onto.");
	case EControlFlowStepKind::Branch:
		return LOCTEXT("HintSwitch", "A Switch step takes a Control Flow Switch: Add Case for each case, then Select Case.");
	case EControlFlowStepKind::Fork:
		return LOCTEXT("HintParallel", "A Parallel step takes a Control Flow Parallel: Add Track for each track that runs at the same time.");
	case EControlFlowStepKind::Race:
		return LOCTEXT("HintRace", "A Race step takes a Control Flow Parallel, like a Parallel step: Add Track for each track. The first track to finish wins; the others are cancelled.");
	case EControlFlowStepKind::Loop:
		return LOCTEXT("HintLoop", "A Loop step takes a Control Flow Loop: Get Body to build the iteration, Continue Looping to answer.");
	default:
		return FText::GetEmpty();
	}
}

bool UK2Node_QueueControlFlowStep::CanCreateMatchingEvent() const
{
	const UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this);
	return Blueprint && FBlueprintEditorUtils::FindEventGraph(Blueprint) && GetDelegateSignature(StepKind, false);
}

UK2Node_CustomEvent* UK2Node_QueueControlFlowStep::CreateMatchingEvent()
{
	UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this);

	const UFunction* Signature = GetDelegateSignature(StepKind, false);
	if (!Blueprint || !Signature)
	{
		return nullptr;
	}

	const FScopedTransaction Transaction(LOCTEXT("CreateMatchingEvent", "Create Matching Step Event"));
	Modify();

	const FString KindName = StaticEnum<EControlFlowStepKind>()->GetDisplayNameTextByValue(static_cast<int64>(StepKind)).ToString().Replace(TEXT(" "), TEXT(""));
	UK2Node_CustomEvent* Event = UE::ControlFlowBP::NodeUtils::AddMatchingEvent(Blueprint, Signature, KindName + TEXT("Step"));
	if (!Event)
	{
		return nullptr;
	}

	SetFunctionInternal(Event->CustomFunctionName);
	FunctionGuid = Event->NodeGuid;

	FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified(Blueprint);
	return Event;
}

bool UK2Node_QueueControlFlowStep::IsFunctionPin(const UEdGraphPin& Pin) const
{
	return Pin.PinName == PN_Function && Pin.Direction == EGPD_Input;
}

TArray<FName> UK2Node_QueueControlFlowStep::GetPickableFunctions(const UEdGraphPin&) const
{
	return GetCandidateFunctions();
}

FText UK2Node_QueueControlFlowStep::GetCreateFunctionLabel(const UEdGraphPin&) const
{
	if (!CanCreateMatchingEvent())
	{
		return FText::GetEmpty();
	}

	return FText::Format(LOCTEXT("CreateMatchingEventOption", "[Create a matching {0} event]"),
		StaticEnum<EControlFlowStepKind>()->GetDisplayNameTextByValue(static_cast<int64>(StepKind)));
}

UObject* UK2Node_QueueControlFlowStep::CreateFunctionFor(const UEdGraphPin&)
{
	return CreateMatchingEvent();
}

FText UK2Node_QueueControlFlowStep::GetNoFunctionsLabel(const UEdGraphPin&) const
{
	return FText::Format(LOCTEXT("NoFunctions", "(no {0} functions on this Blueprint yet)"),
		StaticEnum<EControlFlowStepKind>()->GetDisplayNameTextByValue(static_cast<int64>(StepKind)));
}

FText UK2Node_QueueControlFlowStep::GetFunctionPinHint(const UEdGraphPin&) const
{
	return FText::Format(LOCTEXT("FunctionPinHint", "Functions and custom events on this Blueprint that fit the Step Kind.\n{0}"), GetSignatureHint(StepKind));
}

UObject* UK2Node_QueueControlFlowStep::GetFunctionDefinition(const UEdGraphPin&) const
{
	return GetJumpTargetForDoubleClick();
}

void UK2Node_QueueControlFlowStep::ReconstructNode()
{
	FName NewName;
	if (FindRenamedFunction(NewName))
	{
		FunctionName = NewName;
	}

	FollowFunctionKind();

	Super::ReconstructNode();
}

void UK2Node_QueueControlFlowStep::PostReconstructNode()
{
	Super::PostReconstructNode();

	MirrorPropertiesToPins();
}

bool UK2Node_QueueControlFlowStep::FindRenamedFunction(FName& OutNewName) const
{
	FName ResolvedName;
	if (FunctionName.IsNone() || !ResolveStepFunction(&ResolvedName) || ResolvedName == FunctionName)
	{
		return false;
	}

	OutNewName = ResolvedName;
	return true;
}

void UK2Node_QueueControlFlowStep::HandleFunctionRenamed(UBlueprint* InBlueprint, UClass* InFunctionClass, UEdGraph* InGraph, const FName& InOldFuncName, const FName& InNewFuncName)
{
	Super::HandleFunctionRenamed(InBlueprint, InFunctionClass, InGraph, InOldFuncName, InNewFuncName);

	if (ReferencesFunction(InOldFuncName, InFunctionClass))
	{
		Modify();
		FunctionName = InNewFuncName;
		MirrorPropertiesToPins();
	}
}

void UK2Node_QueueControlFlowStep::ClearCachedBlueprintData(UBlueprint* Blueprint)
{
	Super::ClearCachedBlueprintData(Blueprint);

	FName NewName;
	if (FindRenamedFunction(NewName))
	{
		Modify();
		FunctionName = NewName;
		MirrorPropertiesToPins();
	}
}

bool UK2Node_QueueControlFlowStep::ReferencesFunction(const FName& InFunctionName, const UStruct* InScope) const
{
	using namespace UE::ControlFlowBP;

	return StepKind != EControlFlowStepKind::Delay
		&& !FunctionName.IsNone()
		&& FunctionName == InFunctionName
		&& NodeUtils::IsClassOrChildOf(NodeUtils::GetSearchClass(FBlueprintEditorUtils::FindBlueprintForNode(this)), InScope);
}

void UK2Node_QueueControlFlowStep::ValidateNodeDuringCompilation(FCompilerResultsLog& MessageLog) const
{
	Super::ValidateNodeDuringCompilation(MessageLog);

	if (StepKind == EControlFlowStepKind::Delay)
	{
		return;
	}

	if (FunctionName.IsNone())
	{
		MessageLog.Error(*LOCTEXT("NoFunction", "@@: pick the function this step runs.").ToString(), this);
		return;
	}

	FName ResolvedName;
	const UFunction* Function = ResolveStepFunction(&ResolvedName);
	if (!Function)
	{
		MessageLog.Error(*FText::Format(
			LOCTEXT("MissingFunction", "@@: '{0}' does not exist on this Blueprint."),
			FText::FromName(FunctionName)).ToString(), this);
		return;
	}

	FString Why;
	const EControlFlowStepKind Actual = ResolveKind(UControlFlowBP::DeduceStepKind(Function, Why), StepKind);
	if (Actual == EControlFlowStepKind::Invalid)
	{
		MessageLog.Error(*FText::Format(
			LOCTEXT("BadSignature", "@@: '{0}' cannot be a control flow step - {1}."),
			FText::FromName(ResolvedName), FText::FromString(Why)).ToString(), this);
		return;
	}

	if (!IsBindable(Function, Actual))
	{
		MessageLog.Error(*FText::Format(
			LOCTEXT("NotBindable", "@@: '{0}' has the right parameter type for a {1} step, but not the exact signature - make sure the parameter is not passed by reference."),
			FText::FromName(ResolvedName),
			StaticEnum<EControlFlowStepKind>()->GetDisplayNameTextByValue(static_cast<int64>(Actual))).ToString(), this);
		return;
	}

	if (Actual != StepKind)
	{
		const UEnum* KindEnum = StaticEnum<EControlFlowStepKind>();
		MessageLog.Warning(*FText::Format(
			LOCTEXT("KindChanged", "@@: '{0}' is now a {1} step, not a {2} step, and compiles as {1}. Refresh the node to update its pins."),
			FText::FromName(ResolvedName),
			KindEnum->GetDisplayNameTextByValue(static_cast<int64>(Actual)),
			KindEnum->GetDisplayNameTextByValue(static_cast<int64>(StepKind))).ToString(), this);
	}
}

void UK2Node_QueueControlFlowStep::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UEdGraphPin* TargetPin = FindPin(PN_Target);
	if (!TargetPin || TargetPin->LinkedTo.Num() == 0)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("NoTarget", "@@ needs a Control Flow on its @@ pin.").ToString(), this, TargetPin);

		BreakAllNodeLinks();
		return;
	}

	FName ResolvedName;
	const UFunction* StepFunction = nullptr;
	EControlFlowStepKind Kind = EControlFlowStepKind::Delay;
	if (StepKind != EControlFlowStepKind::Delay)
	{
		StepFunction = ResolveStepFunction(&ResolvedName);

		FString Unused;
		Kind = StepFunction ? ResolveKind(UControlFlowBP::DeduceStepKind(StepFunction, Unused), StepKind) : EControlFlowStepKind::Invalid;
	}

	if (Kind == EControlFlowStepKind::Invalid)
	{
		BreakAllNodeLinks();
		return;
	}

	if (Kind == EControlFlowStepKind::Function && StepFunction->NumParms == 0)
	{
		UEdGraphPin* PayloadPin = FindPin(PN_Payload);
		if (PayloadPin && PayloadPin->LinkedTo.Num() > 0)
		{
			CompilerContext.MessageLog.Warning(*FText::Format(
				LOCTEXT("PayloadIgnored", "@@: '{0}' takes no parameters, so its @@ is ignored. Give the event an Instanced Struct input to receive it."),
				FText::FromName(ResolvedName)).ToString(), this, PayloadPin);
		}
	}

	const FQueueCall Call = GetQueueCall(Kind, StepFunction && StepFunction->NumParms > 0);
	UFunction* QueueFunction = UControlFlowBP::StaticClass()->FindFunctionByName(Call.Function);
	if (!QueueFunction)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("NoQueueFunction", "@@: internal error - the Control Flow queue function is missing.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	bool bSucceeded = true;

	UK2Node_CallFunction* CallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	CallNode->SetFromFunction(QueueFunction);
	CallNode->AllocateDefaultPins();

	const auto MoveToCall = [this, CallNode, &CompilerContext, &bSucceeded](FName FromPinName, FName ToPinName) -> void
	{
		UEdGraphPin* FromPin = FindPin(FromPinName);
		UEdGraphPin* ToPin = CallNode->FindPin(ToPinName);
		if (!FromPin || !ToPin)
		{
			bSucceeded = false;
			return;
		}

		bSucceeded &= CompilerContext.MovePinLinksToIntermediate(*FromPin, *ToPin).CanSafeConnect();
	};

	MoveToCall(UEdGraphSchema_K2::PN_Execute, UEdGraphSchema_K2::PN_Execute);
	MoveToCall(UEdGraphSchema_K2::PN_Then, UEdGraphSchema_K2::PN_Then);
	MoveToCall(PN_Target, UEdGraphSchema_K2::PN_Self);
	MoveToCall(PN_Flow, UEdGraphSchema_K2::PN_ReturnValue);
	MoveToCall(PN_StepName, Call.NameParam);

	if (Call.bTakesPayload)
	{
		MoveToCall(PN_Payload, PN_Payload);
	}

	static const FName TimeoutParam(TEXT("TimeoutSeconds"));
	static const FName ModeParam(TEXT("Mode"));
	static const FName MaxIterationsParam(TEXT("MaxIterations"));
	static const FName SecondsParam(TEXT("Seconds"));

	switch (Kind)
	{
	case EControlFlowStepKind::Wait:
		if (FindPin(PN_TimeoutSeconds))
		{
			MoveToCall(PN_TimeoutSeconds, TimeoutParam);
		}
		break;

	case EControlFlowStepKind::Fork:
		if (FindPin(PN_ForkMode))
		{
			MoveToCall(PN_ForkMode, ModeParam);
		}
		break;

	case EControlFlowStepKind::Loop:
		if (FindPin(PN_LoopMode))
		{
			MoveToCall(PN_LoopMode, ModeParam);
		}
		else if (UEdGraphPin* CallModePin = CallNode->FindPin(ModeParam))
		{
			CallModePin->DefaultValue = StaticEnum<EControlFlowLoopMode>()->GetNameStringByValue(static_cast<int64>(EControlFlowLoopMode::DoWhile));
		}

		if (FindPin(PN_MaxIterations))
		{
			MoveToCall(PN_MaxIterations, MaxIterationsParam);
		}
		break;

	case EControlFlowStepKind::Delay:
		MoveToCall(PN_Seconds, SecondsParam);
		break;

	default:
		break;
	}

	if (!Call.DelegateParam.IsNone())
	{
		UK2Node_Self* SelfNode = CompilerContext.SpawnIntermediateNode<UK2Node_Self>(this, SourceGraph);
		SelfNode->AllocateDefaultPins();

		UK2Node_CreateDelegate* CreateDelegateNode = CompilerContext.SpawnIntermediateNode<UK2Node_CreateDelegate>(this, SourceGraph);
		CreateDelegateNode->AllocateDefaultPins();

		UEdGraphPin* DelegateParamPin = CallNode->FindPin(Call.DelegateParam);
		bSucceeded &= DelegateParamPin && Schema->TryCreateConnection(CreateDelegateNode->GetDelegateOutPin(), DelegateParamPin);
		bSucceeded &= Schema->TryCreateConnection(SelfNode->FindPinChecked(UEdGraphSchema_K2::PN_Self), CreateDelegateNode->GetObjectInPin());

		CreateDelegateNode->SetFunction(ResolvedName);
	}

	if (!bSucceeded)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("ExpansionFailed", "@@: internal error while expanding the step.").ToString(), this);
	}

	BreakAllNodeLinks();
}

FText UK2Node_QueueControlFlowStep::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::MenuTitle)
	{
		return LOCTEXT("MenuTitle", "Queue Step");
	}

	const FText KindText = StaticEnum<EControlFlowStepKind>()->GetDisplayNameTextByValue(static_cast<int64>(StepKind));
	if (FunctionName.IsNone() || StepKind == EControlFlowStepKind::Delay)
	{
		return FText::Format(LOCTEXT("TitleNoFunction", "Queue Step\n{0}"), KindText);
	}

	return FText::Format(LOCTEXT("Title", "Queue Step\n{0}: {1}"), KindText, FText::FromName(FunctionName));
}

FText UK2Node_QueueControlFlowStep::GetTooltipText() const
{
	return LOCTEXT("Tooltip",
		"Queues a step that runs one of this Blueprint's functions or custom events - or, with Step Kind set to Delay, one that "
		"waits Seconds of game time.\n\n"
		"Step Kind filters the Function dropdown to the functions whose signature fits, and the signature is checked when the "
		"Blueprint compiles - so a function with the wrong signature is a compile error, not a runtime one.\n\n"
		"Add or remove the handle/scope parameter on the event and the node follows it to the new kind.\n\n"
		"If, Wait Until, Wait For Event Dispatcher, Repeat and For Each have Queue nodes of their own.");
}

FText UK2Node_QueueControlFlowStep::GetKeywords() const
{
	return LOCTEXT("Keywords", "control flow queue step function wait switch branch case parallel fork track loop sub flow sequence delay timer seconds");
}

FLinearColor UK2Node_QueueControlFlowStep::GetNodeTitleColor() const
{
	return FLinearColor(0.190525f, 0.583898f, 1.0f);
}

FSlateIcon UK2Node_QueueControlFlowStep::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = GetNodeTitleColor();
	static const FSlateIcon Icon(FAppStyle::GetAppStyleSetName(), TEXT("Kismet.AllClasses.FunctionIcon"));
	return Icon;
}

UObject* UK2Node_QueueControlFlowStep::GetJumpTargetForDoubleClick() const
{
	FName ResolvedName;
	ResolveStepFunction(&ResolvedName);

	return UE::ControlFlowBP::NodeUtils::FindFunctionDefinition(FBlueprintEditorUtils::FindBlueprintForNode(this), ResolvedName);
}

bool UK2Node_QueueControlFlowStep::IsCompatibleWithGraph(const UEdGraph* TargetGraph) const
{
	const UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForGraph(TargetGraph);
	if (!Blueprint
		|| Blueprint->BlueprintType == BPTYPE_FunctionLibrary
		|| Blueprint->BlueprintType == BPTYPE_MacroLibrary
		|| Blueprint->BlueprintType == BPTYPE_Interface)
	{
		return false;
	}

	return Super::IsCompatibleWithGraph(TargetGraph);
}

void UK2Node_QueueControlFlowStep::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(ActionKey);
		check(NodeSpawner);
		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

FText UK2Node_QueueControlFlowStep::GetMenuCategory() const
{
	return LOCTEXT("MenuCategory", "Control Flow|Queue");
}

#undef LOCTEXT_NAMESPACE
